Sprint 1/step 1
shshchkn/react-burger pull request #1
Opened 2022-10-02 20:47 UTC by shshchkn

2022-10-02 21:53 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.tsx
> +
**Можно лучше:** В будущем оберните это в useMemo

2022-10-02 21:53 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +      <Tab value="bun" active={current === 'bun'} onClick={setCurrent}>Булки</Tab>
**Можно лучше:** Обработчик событий лучше вынести в отдельную функцию, а также сделать скролл, по клику на таб, до нужной сецкии.

Например: 
```js 
const onTabClick = (tab) => {
  setCurrentTab(tab);
  const element = document.getElementById(tab);
  if (element) element.scrollIntoView({ behavior: "smooth" });
};
```

2022-10-02 21:57 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.
### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

- Компонент header по чек-листу, должен называться AppHeader.

### **Сделает код лучше:**

- Лучше не делать много компонентов в 1 компоненте, лучше создать подпапку `components`.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Более мелкие мелкие замечания, отмечены в коде._**

2022-10-03 07:19 UTC, shshchkn commented on src/components/burger-constructor/BurgerConstructor.tsx
> +
Ок, учту этот момент

2022-10-03 09:41 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы! Можете приступать к финально сдачи задачи.**

- Почти все замечания с 1 ревью, были исправлены.

### **Но есть 1 новое замечание, которое нужно исправить:**

- Нужно удалить файл App.test.tsx. Пока что вы не будете делать тесты, но в будущем вы к этому вернётесь.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-03 09:41 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  const items = data.filter(item => item.type !== 'bun');
**Можно лучше:** Здесь больше подходит метод find.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2022-10-03 18:13 UTC, shshchkn commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  const items = data.filter(item => item.type !== 'bun');
App.test.tsx удалил, переписал на find в конструкторе, но не уверен за правильность, т.к. с TypeScript до этого не работал)

2022-10-04 16:09 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  const items = data.filter(item => item.type !== 'bun');
У вас всё отлично!) Можете приступать к финальной сдаче задания.

2022-10-04 16:10 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы! Можете приступать к финальной сдачи задания.**

- Все замечания с прошлого ревью, были исправлены.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-10-04 17:06 UTC, merged