Sprint 1/step 2
shshchkn/react-burger pull request #2
Opened 2022-10-09 16:06 UTC by shshchkn

Очень долго бился с типами Typescript, поэтому местами any применил.
Не все до конца понял, тут скорее в чате помогли, в частности с IngredientsDetails.

2022-10-10 10:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Конечно на данном этапе, от вас не буду требовать идеального использования typescript. Но попробуйте проконсультироваться с наставником)) он вам подскажет как правильнее оформить некоторые типы, и пропсы.

### **Но есть несколько замечаний, которые нужно исправить:**

- поправить работу с сервером.

- поправить логику модального окна.

### **Сделает код лучше:**

- В компоненте `app-header` лучше не делать такое сильно разделение. Там достаточно простая структура, и её можно не делить на разные компоненты, а в будущем вы будете использовать для ссылок компоненты от react-router. И у вас тогда получается ситуация, компонент для компонента.

- В некоторых компонентах, содержится по несколько компонентов в 1 файле. Лучше вынести их в подпапку `components`. Тогда вам будет намного легче ориентироваться в коде и поддерживать его.

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +const dataUrl = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**

имена констант принято записывать в стиле UPPER_CASE

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте
**Можно лучше**
вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +    setState({...state, loading: true});
**Можно лучше:** немного не понял, зачем тут еще раз делать loading `true`. Если у нас изначально он `true`, и `useEffect` будет выполняться всего 1 раз.

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +                      <img src={loader} alt=""/>
**Надо исправить:** Если в проекте используются сторонние шрифты или изображения, то они хранятся в папках fonts и images;

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  ), [products]);
**Можно лучше:** Тут, кажется, вы немного перепутали зависимости. В зависимостях должно быть `items`

2022-10-10 10:43 UTC, ArslanMustafin commented on src/components/modal/Modal.tsx
> +  const [isOpen, setIsOpen] = useState(show);
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг. Уточню что это не должно делаться в компонент `modal`, делайте это в компонентах, где используете `modal`.

```
{isOpen && (
    компонент открываемого попапа
)}
``

2022-10-10 10:43 UTC, ArslanDev666 commented on src/components/modal/Modal.tsx
> +  const [isLoading, setIsLoading] = useState(true);
**Можно лучше:** Не до конца понимаю, зачем тут нужен loading, У нас ведь нет здесь асинхронного кода, значит и ждать нечего))

2022-10-10 18:12 UTC, shshchkn commented on src/components/app/App.tsx
> +const dataUrl = 'https://norma.nomoreparties.space/api/ingredients';
Ок, видимо пропустил данный факт

2022-10-10 18:38 UTC, shshchkn commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
В таком порядке данные почему-то не приходят, хотя state по идее сохраняется 

`useEffect(() => {
    const getProducts = () => fetch(`${API_URL}/ingredients`).then(checkApiResponse);
    getProducts()
      .then(res => setState({...state, data: res.data}))
      .catch(err => console.log(err))
      .finally(() => setState({...state, loading: false}));
  }, []);`
  
пока вернул как было, до уточнения

2022-10-10 18:43 UTC, shshchkn commented on src/components/app/App.tsx
> +    setState({...state, loading: true});
Тут, да, лишняя строка)

2022-10-10 18:44 UTC, shshchkn commented on src/components/app/App.tsx
> +                      <img src={loader} alt=""/>
Переместил как положено в images

2022-10-10 18:47 UTC, shshchkn commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  ), [products]);
Согласен, не доглядел

2022-10-10 19:07 UTC, shshchkn commented on src/components/modal/Modal.tsx
> +  const [isOpen, setIsOpen] = useState(show);
Поменял, но не совсем понял, по чек-листу открытие/закрытие вроде как должно находиться в компоненте Modal

2022-10-10 19:08 UTC, shshchkn commented on src/components/modal/Modal.tsx
> +  const [isLoading, setIsLoading] = useState(true);
Да пытался красиво лоадер сделать)
Убрал

2022-10-10 20:35 UTC, ArslanDev666 commented on src/components/modal/Modal.tsx
> +  const [isOpen, setIsOpen] = useState(show);
в модалке должна быть только подписка на событие закрытия по клавише esc. В оверлее, там просто на onClick нужно навесить onClose. А в компонентах контролировать модалку, тем способом, который я написал в комментариях)) так у нас будет больше возможностей для модернизации кода, и не будет привязки функционала к модалке.

2022-10-10 20:39 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
А покажите функцию chechApiResponse

2022-10-10 21:49 UTC, shshchkn commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
> А покажите функцию checkApiResponse

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```
<img width="759" alt="image" src="https://user-images.githubusercontent.com/7847378/194957284-5b297647-32e6-4c96-bba2-95e1bc42c4ce.png">

2022-10-11 14:50 UTC, shshchkn commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
Т.е. получается ответ от сервера пришел, но в state данные не попадают)

<img width="872" alt="image" src="https://user-images.githubusercontent.com/7847378/195124320-5711113a-fea0-4362-aa1b-4284c0b0bf3e.png">
![image](https://user-images.githubusercontent.com/7847378/195124504-76665385-2255-45ff-85d7-57309dd051dc.png)

2022-10-11 14:52 UTC, shshchkn commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
![image](https://user-images.githubusercontent.com/7847378/195125178-bb7d2e55-635c-40e0-ba2e-65a014740b77.png)

2022-10-11 16:40 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
а если лог сделать в самом компоненте, потому что SetState отработает после того как выполнится лог.

2022-10-11 17:05 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  }, [state]);
**Надо исправить:** Тут должен быть пустой массив, а то вы сейчас в бесконечную рекурсию вошли)) исправите, и я гляну ревью сразу.

2022-10-11 17:18 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы, задание принято. Удачи в дальнейшем обучении!**

### **Сделает код лучше:**

- Не забудьте исправить бесконечный запрос в компоненте App.

2022-10-11 17:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +        <ProductsList data={products} showModal={handleOpenModal} title="Начинки" type="main"/>
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив. В вашем случае просто передавать в пропс data.
Так мы сделаем приложение более оптимизированно, ведь фильтрация не будет выполняться каждый ререндер.

Например:

```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
```

А не располагать фильтрацию в самом jsx

2022-10-11 17:18 UTC, ArslanDev666 commented on src/components/modal/Modal.tsx
> +          {headerTitle && headerTitle}
**Можно лучше:** Тут лучше написать вот так `headerTitle || null`

2022-10-11 17:18 UTC, ArslanDev666 commented on src/components/modal/Modal.tsx
> +    }
**можно лучше:** не оч понимаю зачем тут условие, если у нас модальное окно рендериться вот таким способом:
```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-10-11 17:51 UTC, shshchkn commented on src/components/app/App.tsx
> +      .catch(err => console.log(err));
> а если лог сделать в самом компоненте?, потому что SetState отработает после того как выполнится лог, поэтому он и пустой.

Если оставляю finally получаю null

2022-10-11 17:53 UTC, shshchkn commented on src/components/app/App.tsx
> +  }, [state]);
> **Надо исправить:** Тут должен быть пустой массив, а то вы сейчас в бесконечную рекурсию вошли)). Кроме этого, больше нет критических замечаний, поэтому принял работу. И надеюсь вы исправите этот момент в будущем.

Да, это я тестил вывод в консоль по разному, не знаю как он в гит попал, но сейчас его нет

2022-10-11 17:59 UTC, shshchkn commented on src/components/modal/Modal.tsx
> +    }
> **можно лучше:** не оч понимаю зачем тут условие, если у нас модальное окно рендериться вот таким способом:
> 
> ```js
> {isOpen && (
>     компонент открываемого попапа
> )}
> ```

На show завязан класс для анимации, а также убираю скролл у body

2022-10-11 17:59 UTC, shshchkn commented on src/components/modal/Modal.tsx
> +          {headerTitle && headerTitle}
> **Можно лучше:** Тут лучше написать вот так `headerTitle || null`

Ага, надо запомнить shorthand)

2022-10-11 18:04 UTC, shshchkn commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +        <ProductsList data={products} showModal={handleOpenModal} title="Начинки" type="main"/>
> **Можно лучше**
> 
> Лучше в компоненте делать filter по массиву, а потом отображать полученный массив. В вашем случае просто передавать в пропс data. Так мы сделаем приложение более оптимизированно, ведь фильтрация не будет выполняться каждый ререндер.
> 
> Например:
> 
> ```
> const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
> const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
> const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
> ```
> 
> А не располагать фильтрацию в самом jsx

Правильно понимаю, я мемоизирую массивы по типу и вместо products передаю  в каждый ProductList  в компоненте BurgerIngredients?

2022-10-11 19:31 UTC, ArslanDev666 commented on src/components/modal/Modal.tsx
> +    }
Там можно без show сделать, компонент ведь каждый раз заново рендериться, так что в show роли вообще не играет. Можно спокойно всё убрать связанное с show.

2022-10-11 19:32 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +        <ProductsList data={products} showModal={handleOpenModal} title="Начинки" type="main"/>
+ да, всё верно.

2022-10-11 19:38 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  }, [state]);
```js
    getProducts()
      .then(res => setState((prevState) => ({ ...prevState, data: res.data, loading: false })))
      .catch(err => console.log(err))
      .finally(() => setState((prevState) => ({ ...prevState, loading: false })));
  }, []);
```

Вот так всё норм будет, почему так, подробне про то как работает useState. https://reactjs.org/docs/hooks-reference.html#functional-updates

2022-10-11 20:01 UTC, shshchkn commented on src/components/app/App.tsx
> +  }, [state]);
> ```js
>     getProducts()
>       .then(res => setState((prevState) => ({ ...prevState, data: res.data, loading: false })))
>       .catch(err => console.log(err))
>       .finally(() => setState((prevState) => ({ ...prevState, loading: false })));
>   }, []);
> ```
> 
> Вот так всё норм будет, почему так?, подробнее про то, как работает useState. https://reactjs.org/docs/hooks-reference.html#functional-updates

ок, видимо я не до конца понял как он сохраняет состояние, отталкивался от уроков)
Только вопрос, а зачем нам в then loading: false, а потом в finally?
Возможно finally тут реально лишний)

2022-10-11 20:03 UTC, shshchkn commented on src/components/modal/Modal.tsx
> +    }
> Там можно без show сделать, компонент ведь каждый раз заново рендериться, так что show роли вообще не играет. Можно спокойно всё убрать связанное с show.

ок, завтра все проверю и смержу тогда

2022-10-12 13:15 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  }, [state]);
Пропустил момент, вот так будет корректнее: 
```js
getProducts()
      .then(res => setState((prevState) => ({ ...prevState, data: res.data})))
      .catch(err => console.log(err))
      .finally(() => setState((prevState) => ({ ...prevState, loading: false })));
```

2022-10-12 15:47 UTC, shshchkn commented on src/components/app/App.tsx
> +  }, [state]);
> Пропустил момент, вот так будет корректнее:
> 
> ```js
> getProducts()
>       .then(res => setState((prevState) => ({ ...prevState, data: res.data})))
>       .catch(err => console.log(err))
>       .finally(() => setState((prevState) => ({ ...prevState, loading: false })));
> ```

Да, супер, так отлично работает!

2022-10-12 15:50 UTC, merged